
POPULAR_TRACKS = {
    'English': [
        ('Fix You', 'Coldplay', ['Sadness', 'Healing', 'Hopefulness'], 44, 2005, 96),
        ('Someone Like You', 'Adele', ['Heartbreak', 'Nostalgia', 'Sadness'], 30, 2011, 97),
        ('Ocean Eyes', 'Billie Eilish', ['Romantic Warmth', 'Serenity', 'Melancholy'], 28, 2016, 93),
        ('Blinding Lights', 'The Weeknd', ['Energy', 'Nostalgia', 'Confidence'], 84, 2019, 100),
        ('Photograph', 'Ed Sheeran', ['Nostalgia', 'Romantic Warmth', 'Melancholy'], 36, 2014, 95),
        ('Lover', 'Taylor Swift', ['Romantic Warmth', 'Hopefulness', 'Serenity'], 44, 2019, 94),
        ('Skinny Love', 'Bon Iver', ['Melancholy', 'Introspection', 'Romantic Warmth'], 36, 2007, 92),
        ('Somebody Else', 'The 1975', ['Nostalgia', 'Loneliness', 'Romantic Warmth'], 54, 2016, 94),
        ('Glimpse of Us', 'Joji', ['Heartbreak', 'Nostalgia', 'Romantic Warmth'], 28, 2022, 95),
        ('Apocalypse', 'Cigarettes After Sex', ['Melancholy', 'Intimacy', 'Serenity'], 30, 2017, 92),
        ('Stay With Me', 'Sam Smith', ['Romantic Warmth', 'Sadness', 'Hopefulness'], 52, 2014, 96),
        ('Do I Wanna Know', 'Arctic Monkeys', ['Melancholy', 'Confidence', 'Nostalgia'], 72, 2013, 95),
        ('Take Me To Church', 'Hozier', ['Emotional Depth', 'Melancholy', 'Romantic Warmth'], 52, 2013, 94),
        ('Summertime Sadness', 'Lana Del Rey', ['Melancholy', 'Nostalgia', 'Romantic Warmth'], 54, 2012, 94),
        ('Watermelon Sugar', 'Harry Styles', ['Excitement', 'Energy', 'Romantic Warmth'], 78, 2019, 95),
        ('Rolling in the Deep', 'Adele', ['Heartbreak', 'Confidence', 'Energy'], 74, 2010, 96),
        ('Set Fire to the Rain', 'Adele', ['Heartbreak', 'Energy', 'Emotional Depth'], 70, 2011, 95),
        ('A Sky Full of Stars', 'Coldplay', ['Hopefulness', 'Energy', 'Excitement'], 86, 2014, 95),
        ('Heat Waves', 'Glass Animals', ['Melancholy', 'Nostalgia', 'Energy'], 70, 2020, 96),
        ('All of Me', 'John Legend', ['Romantic Warmth', 'Serenity', 'Hopefulness'], 38, 2013, 96),
        ('Radioactive', 'Imagine Dragons', ['Confidence', 'Energy', 'Motivation'], 88, 2012, 95),
        ('Stressed Out', 'Twenty One Pilots', ['Anxiety', 'Nostalgia', 'Energy'], 70, 2015, 94),
    ],
    'Hindi': [
        ('Tum Hi Ho', 'Arijit Singh', ['Romantic Warmth', 'Sadness', 'Heartbreak'], 32, 2013, 99),
        ('Channa Mereya', 'Arijit Singh', ['Heartbreak', 'Nostalgia', 'Sadness'], 34, 2016, 99),
        ('Kesariya', 'Arijit Singh', ['Romantic Warmth', 'Hopefulness', 'Warmth'], 52, 2022, 98),
        ('Hawayein', 'Arijit Singh', ['Travel', 'Romantic Warmth', 'Serenity'], 46, 2017, 95),
        ('Tujh Mein Rab Dikhta Hai', 'Shreya Ghoshal', ['Romantic Warmth', 'Serenity', 'Hopefulness'], 34, 2008, 94),
        ('Tadap Tadap', 'KK', ['Heartbreak', 'Anguish', 'Melancholy'], 58, 2010, 93),
        ('Tum Se Hi', 'Mohit Chauhan', ['Romantic Warmth', 'Hopefulness', 'Serenity'], 48, 2006, 94),
        ('Tum Hi Aana', 'Jubin Nautiyal', ['Heartbreak', 'Nostalgia', 'Melancholy'], 38, 2019, 96),
        ('Agar Tum Saath Ho', 'Pritam', ['Heartbreak', 'Romantic Warmth', 'Sadness'], 28, 2015, 99),
        ('Safarnama', 'Lucky Ali', ['Travel', 'Hopefulness', 'Nostalgia'], 42, 2008, 94),
        ('Cold Mess', 'Prateek Kuhad', ['Melancholy', 'Introspection', 'Romantic Warmth'], 38, 2019, 94),
        ('Main Hoon Hero Tera', 'Armaan Malik', ['Confidence', 'Romantic Warmth', 'Hopefulness'], 42, 2014, 93),
        ('Shayad', 'Arijit Singh', ['Romantic Warmth', 'Hopefulness', 'Introspection'], 46, 2020, 96),
        ('Ghungroo', 'Arijit Singh, Shilpa Rao', ['Party', 'Energy', 'Romantic Warmth'], 86, 2019, 95),
        ('Raatan Lambiyan', 'Jubin Nautiyal, Asees Kaur', ['Romantic Warmth', 'Serenity', 'Nostalgia'], 48, 2021, 96),
        ('Ae Dil Hai Mushkil', 'Arijit Singh', ['Heartbreak', 'Sadness', 'Romantic Warmth'], 36, 2016, 95),
        ('Gerua', 'Arijit Singh, Antara Mitra', ['Romantic Warmth', 'Nostalgia', 'Hopefulness'], 54, 2015, 94),
        ('Dil Diyan Gallan', 'Atif Aslam', ['Romantic Warmth', 'Serenity', 'Calmness'], 38, 2017, 95),
        ('Badtameez Dil', 'Benny Dayal, Shefali Alvares', ['Party', 'Energy', 'Confidence'], 90, 2013, 95),
        ('Nashe Si Chadh Gayi', 'Arijit Singh', ['Party', 'Romantic Warmth', 'Energy'], 84, 2016, 94),
        ('Kabira', 'Tochi Raina, Rekha Bhardwaj', ['Nostalgia', 'Hopefulness', 'Emotional Depth'], 56, 2013, 95),
        ('Kal Ho Naa Ho', 'Sonu Nigam', ['Hopefulness', 'Nostalgia', 'Healing'], 42, 2003, 95),
    ],
    'Tamil': [
        ('Naan Pizhai', 'Anirudh Ravichander', ['Confidence', 'Playful', 'Energy'], 82, 2023, 96),
        ('Thalli Pogathey', 'Sid Sriram', ['Romantic Warmth', 'Melancholy', 'Longing'], 54, 2016, 95),
        ('Vande Mataram', 'A.R. Rahman', ['Patriotism', 'Hopefulness', 'Pride'], 78, 2010, 95),
        ('Kannaana Kanney', 'Yuvan Shankar Raja', ['Romantic Warmth', 'Hopefulness', 'Serenity'], 56, 2017, 94),
        ('Iravil', 'Santhosh Narayanan', ['Melancholy', 'Introspection', 'Serenity'], 34, 2022, 93),
        ('Kanave Kanave', 'Anirudh Ravichander', ['Heartbreak', 'Sadness', 'Melancholy'], 28, 2013, 94),
        ('Naanum Rowdy Dhaan', 'Anirudh Ravichander', ['Confidence', 'Energy', 'Playfulness'], 78, 2015, 94),
        ('Kannazhaga', 'Dhanush', ['Romantic Warmth', 'Nostalgia', 'Melancholy'], 38, 2012, 94),
        ('New York Nagaram', 'A.R. Rahman', ['Loneliness', 'Nostalgia', 'Melancholy'], 30, 2006, 94),
        ('Maruvaarthai', 'Sid Sriram', ['Romantic Warmth', 'Melancholy', 'Longing'], 32, 2017, 95),
        ('Why This Kolaveri Di', 'Dhanush, Anirudh Ravichander', ['Party', 'Excitement', 'Energy'], 82, 2011, 98),
        ('Arabic Kuthu', 'Anirudh Ravichander, Jonita Gandhi', ['Party', 'Energy', 'Excitement'], 94, 2022, 97),
        ('Vaathi Coming', 'Anirudh Ravichander, Gana Balachandar', ['Party', 'Energy', 'Confidence'], 96, 2020, 97),
        ('Munbe Vaa', 'Shreya Ghoshal, Naresh Iyer', ['Romantic Warmth', 'Serenity', 'Nostalgia'], 42, 2006, 97),
        ('Aaromale', 'Alphons Joseph, A.R. Rahman', ['Romantic Warmth', 'Melancholy', 'Serenity'], 36, 2010, 94),
        ('Pookkal Pookkum', 'Roop Kumar Rathod, Harini', ['Nostalgia', 'Romantic Warmth', 'Serenity'], 46, 2010, 93),
        ('Adiye', 'Sid Sriram', ['Romantic Warmth', 'Melancholy', 'Hopefulness'], 46, 2013, 92),
        ('Hosanna', 'Vijay Prakash, Suzanne D Mello', ['Romantic Warmth', 'Hopefulness', 'Energy'], 58, 2010, 94),
        ('Aalaporan Thamizhan', 'A.R. Rahman, Kailash Kher', ['Motivation', 'Confidence', 'Energy'], 88, 2017, 93),
        ('Surviva', 'Anirudh Ravichander, Yogi B', ['Motivation', 'Confidence', 'Energy'], 86, 2017, 90),
    ],
    'Telugu': [
        ('Samajavaragamana', 'Sid Sriram', ['Romantic Warmth', 'Hopefulness', 'Energy'], 70, 2019, 98),
        ('Inkem Inkem Inkem Kaavaale', 'Sid Sriram', ['Romantic Warmth', 'Nostalgia', 'Serenity'], 34, 2018, 97),
        ('Naatu Naatu', 'M.M. Keeravani', ['Party', 'Energy', 'Excitement'], 98, 2022, 100),
        ('Priyathama', 'Anurag Kulkarni', ['Romantic Warmth', 'Serenity', 'Melancholy'], 46, 2019, 94),
        ('Dhol Baaje', 'Devi Sri Prasad', ['Party', 'Energy', 'Excitement'], 92, 2016, 94),
        ('Butta Bomma', 'Armaan Malik', ['Romantic Warmth', 'Confidence', 'Energy'], 76, 2020, 98),
        ('Srivalli', 'Sid Sriram', ['Romantic Warmth', 'Hopefulness', 'Calmness'], 58, 2021, 97),
        ('Priyathama Priyathama', 'Chinmayi', ['Romantic Warmth', 'Serenity', 'Melancholy'], 40, 2019, 94),
        ('Undiporaadhey', 'Sid Sriram', ['Romantic Warmth', 'Melancholy', 'Heartbreak'], 34, 2018, 94),
        ('Kalavathi', 'Sid Sriram', ['Romantic Warmth', 'Hopefulness', 'Energy'], 64, 2022, 94),
        ('Pushpa Pushpa', 'Nakash Aziz, Deepak Blue', ['Confidence', 'Energy', 'Party'], 90, 2024, 93),
        ('Saami Saami', 'Mounika Yadav', ['Party', 'Energy', 'Excitement'], 92, 2021, 95),
        ('Ala Vaikunthapurramuloo', 'Sri Krishna, Priya Sisters', ['Hopefulness', 'Energy', 'Joy'], 74, 2020, 92),
        ('Ramuloo Ramulaa', 'Anurag Kulkarni, Mangli', ['Party', 'Energy', 'Excitement'], 92, 2020, 96),
        ('Vachinde', 'Madhu Priya, Ramky', ['Party', 'Joy', 'Energy'], 86, 2017, 94),
        ('Oosupodu', 'Hemachandra', ['Romantic Warmth', 'Calmness', 'Hopefulness'], 46, 2016, 91),
        ('Evare', 'Vijay Yesudas', ['Romantic Warmth', 'Serenity', 'Nostalgia'], 38, 2016, 92),
        ('Pilla Raa', 'Anurag Kulkarni', ['Romantic Warmth', 'Melancholy', 'Heartbreak'], 40, 2018, 93),
        ('Blockbuster', 'Shreya Ghoshal, Nakash Aziz', ['Party', 'Confidence', 'Energy'], 92, 2016, 90),
        ('Dheevara', 'Ramya Behara, Deepu', ['Motivation', 'Energy', 'Hopefulness'], 78, 2015, 92),
        ('My Love Is Gone', 'Devi Sri Prasad', ['Heartbreak', 'Energy', 'Melancholy'], 70, 2012, 90),
    ],
    'Kannada': [
        ('Ninna Nenapu', 'Vijay Prakash', ['Nostalgia', 'Romantic Warmth', 'Calmness'], 42, 2017, 97),
        ('Nee Hogi Baa', 'Sanjith Hegde', ['Romantic Warmth', 'Hopefulness', 'Serenity'], 42, 2020, 94),
        ('Mysore Se Aayi', 'Raghu Dixit', ['Travel', 'Hopefulness', 'Folk'], 54, 2011, 93),
        ('Manasaare', 'Vasuki Vaibhav', ['Romantic Warmth', 'Calmness', 'Hopefulness'], 42, 2020, 94),
        ('Ee Bindu', 'Anuradha Bhat', ['Hopefulness', 'Calmness', 'Romantic Warmth'], 42, 2010, 92),
        ('Kaadhal', 'Armaan Malik', ['Romantic Warmth', 'Nostalgia', 'Melancholy'], 40, 2013, 92),
        ('Belageddu', 'Vijay Prakash', ['Romantic Warmth', 'Hopefulness', 'Energy'], 72, 2016, 96),
        ('Bombe Helutaithe', 'Vijay Prakash', ['Hopefulness', 'Emotional Depth', 'Nostalgia'], 52, 2017, 97),
        ('Karabuu', 'Chandan Shetty', ['Party', 'Confidence', 'Energy'], 92, 2020, 94),
        ('Open The Bottle', 'Vijay Prakash', ['Party', 'Energy', 'Excitement'], 90, 2013, 92),
        ('Hands Up', 'Vijay Prakash, Shashank Sheshagiri', ['Party', 'Energy', 'Confidence'], 88, 2019, 92),
        ('Soul of Dia', 'Sanjith Hegde, Chinmayi', ['Romantic Warmth', 'Melancholy', 'Serenity'], 34, 2020, 96),
        ('Neene Modalu', 'Sonu Nigam', ['Romantic Warmth', 'Nostalgia', 'Calmness'], 42, 2006, 94),
        ('Anisuthide', 'Sonu Nigam', ['Romantic Warmth', 'Nostalgia', 'Serenity'], 38, 2006, 96),
        ('Ondu Malebillu', 'Armaan Malik, Shreya Ghoshal', ['Romantic Warmth', 'Hopefulness', 'Serenity'], 46, 2017, 93),
        ('Appa I Love You Pa', 'Puneeth Rajkumar', ['Emotional Depth', 'Nostalgia', 'Hopefulness'], 42, 2018, 90),
        ('Gombe Helutaithe', 'Vijay Prakash, Ananya Bhat', ['Romantic Warmth', 'Tradition', 'Energy'], 70, 2022, 94),
        ('Yaare Yaare', 'Armaan Malik', ['Romantic Warmth', 'Calmness', 'Hopefulness'], 44, 2016, 89),
        ('Power of Youth', 'Puneeth Rajkumar', ['Motivation', 'Confidence', 'Energy'], 82, 2014, 91),
        ('Ninna Snehadinda', 'Sonu Nigam', ['Nostalgia', 'Romantic Warmth', 'Serenity'], 40, 2010, 90),
    ],
}
